<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update User</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="../../js/form.js"></script>
    <script src="../../js/updateUser.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-3 align-self-center">
            <div class="form-group">
                <label>Name:</label>
                <input type="text" class="name form-control form-control-sm" placeholder="Enter Name" value="<?php echo $user->getName()?>">
            </div>
            <div class="name-warning alert alert-danger"></div>
            <div class="form-group">
                <label>E-mail:</label>
                <input type="text" class="email form-control form-control-sm" placeholder="Enter E-mail" value="<?php echo $user->getEmail()?>">
            </div>
            <div class="email-warning alert alert-danger"></div>
            <div class="form-group">
                <label>Phone number:</label>
                <input type="text" class="number form-control form-control-sm" placeholder="Enter Phone number" value="<?php echo $user->getNumber()?>">
            </div>
            <div class="form-group">
                <label>City:</label>
                <input type="text" class="city form-control form-control-sm" placeholder="Enter City" value="<?php echo $user->getCity()?>">
            </div>
            <div class="form-group">
                <label>Address:</label>
                <input type="text" class="address form-control form-control-sm" placeholder="Enter Address" value="<?php echo $user->getAddress()?>">
            </div>
            <div>
                <input type="hidden" class="id" value="<?php echo $user->getId();?>">
            </div>
            <div class="text-center">
                <button class="submit btn btn-lg btn-primary">Update User</button>
            </div>
        </div>
    </div>
</div>
</body>
</html>