<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-2">Name:</div>
            <div class="col-2"><?php echo $user->getName();?></div>
        </div>
        <div class="row justify-content-center">
            <div class="col-2">E-mail:</div>
            <div class="col-2"><?php echo $user->getEmail();?></div>
        </div>
        <div class="row justify-content-center">
            <div class="col-2">Phone number:</div>
            <div class="col-2"><?php echo $user->getNumber();?></div>
        </div>
        <div class="row justify-content-center">
            <div class="col-2">City:</div>
            <div class="col-2"><?php echo $user->getCity();?></div>
        </div>
        <div class="row justify-content-center">
            <div class="col-2">Address:</div>
            <div class="col-2"><?php echo $user->getAddress();?></div>
        </div>
    </div>
</body>
</html>